# https://moonrepo.dev/docs/config/project
$schema: 'https://moonrepo.dev/schemas/project.json'

type: 'application'
language: 'typescript' # Changing from Go to TypeScript for Deno

fileGroups:
  sources:
    - 'src/**/*'
  tests:
    - 'tests/**/*'
  configs:
    - '*.json'
    - '*.ts'

# We'll use Deno instead of Go
toolchain:
  deno:
    enabled: true

tasks:
  dev:
    command: 'deno run --watch --allow-net --allow-read --allow-env --allow-run ./src/main.ts'
    local: true
    options:
      persistent: true

  build:
    command: 'deno compile --allow-net --allow-read --allow-env --allow-run --output ./bin/radas-cli ./src/main.ts'
    inputs:
      - '@globs(sources)'
    outputs:
      - 'bin/radas-cli'

  lint:
    command: 'deno lint'
    inputs:
      - '@globs(sources)'
      - '@globs(configs)'

  format:
    command: 'deno fmt'
    inputs:
      - '@globs(sources)'
      - '@globs(configs)'

  test:
    command: 'deno test --allow-net --allow-read --allow-env --allow-run'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'
    deps:
      - '~:lint' 