package main

import (
	"fmt"
	"os"
	"time"
	"sort"
    "strings"
	"github.com/spf13/cobra"
	
	"radas/cmd/frontend"
	"radas/cmd/backend"
	"radas/cmd/design"
	"radas/cmd/devops"
	"radas/cmd/rootcmd"
	"radas/constants"
	"radas/internal/updater"
)

var (
	projectFlag string
	envFlag     string
)

func main() {
	// Handle aliases if first argument is an alias
	handleAliases()
	
	// Root command
	rootCmd := &cobra.Command{
		Use:   "radas",
		Short: "Radas CLI - Developer Tools",
		Long: constants.RadasASCIIArt + `
Radas CLI provides tools for various development teams.
It includes commands for Frontend (fe), Backend (be), DevOps, and Design teams.`,
		Version: constants.Version,
	}

	// Auto-check for updates but only print a message
	go func() {
		release, hasUpdate, err := updater.CheckForUpdate()
		if err == nil && hasUpdate {
			fmt.Printf("\nNew version %s available! Run 'radas update' to upgrade.\n\n", 
				strings.TrimPrefix(release.TagName, "v"))
		}
	}()



	rootCmd.AddCommand(rootcmd.ConfigCmd)

	// Add team commands to root
	rootCmd.AddCommand(frontend.Cmd)
	rootCmd.AddCommand(backend.Cmd)
	rootCmd.AddCommand(devops.Cmd)
	rootCmd.AddCommand(design.Cmd)
	rootCmd.AddCommand(rootcmd.InstallCmd)

	// Add sync-repo command
	rootCmd.AddCommand(rootcmd.SyncRepoCmd)

	// Add update command
	rootCmd.AddCommand(rootcmd.UpdateCmd)

	// Add version command
	rootCmd.AddCommand(rootcmd.VersionCmd)
	
	// Add aliases command
	rootCmd.AddCommand(rootcmd.AliasesCmd)

	rootCmd.AddCommand(rootcmd.EnvCmd)
	rootCmd.AddCommand(rootcmd.RebuildCmd)
	rootCmd.AddCommand(rootcmd.SyncConfigCmd)

	// GIT commands
	rootCmd.AddCommand(rootcmd.CommitCmd)
	rootCmd.AddCommand(rootcmd.PushCmd)
	rootCmd.AddCommand(rootcmd.CreateBranchCmd)
	rootCmd.AddCommand(rootcmd.PullCmd)
	rootCmd.AddCommand(rootcmd.JustPushCmd)
	rootCmd.AddCommand(rootcmd.ListBranchCmd)
	rootCmd.AddCommand(rootcmd.DelBranchCmd)
	rootCmd.AddCommand(rootcmd.CloneCmd)
	rootCmd.AddCommand(rootcmd.GotoCmd)

	
	rootCmd.AddCommand(rootcmd.DoctorCmd)

	// Execute
	if err := rootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

// handleAliases checks if the first argument is an alias and replaces it with the full command
func handleAliases() {
	// Need at least one argument (the alias)
	if len(os.Args) < 2 {
		return
	}
	
	// Check if the first argument is an alias
	alias := os.Args[1]
	if fullCommand, exists := constants.CommandAliases[alias]; exists {
		// Split the full command into parts
		cmdParts := strings.Split(fullCommand, " ")
		
		// Create a new args slice with "radas" as the program name,
		// followed by the expanded command parts,
		// followed by any additional args provided by the user
		newArgs := make([]string, 0, len(cmdParts) + len(os.Args) - 1)
		newArgs = append(newArgs, os.Args[0]) // Program name (radas)
		newArgs = append(newArgs, cmdParts...) // Expanded command
		
		// Add any additional arguments that were provided (if any)
		if len(os.Args) > 2 {
			newArgs = append(newArgs, os.Args[2:]...)
		}
		
		// Replace os.Args with the new arguments
		os.Args = newArgs
		
		// Print a message to show the alias expansion (optional)
		fmt.Printf("Using alias: %s → radas %s\n\n", alias, fullCommand)
	}
}

// Add this function to create .env files
func createEnvFile(envVars map[string]interface{}, projectName, envName string) error {
    // Create filename based on project and environment
    filename := fmt.Sprintf(".env.%s", envName)
    
    // Prepare content for .env file
    var content strings.Builder
    content.WriteString(fmt.Sprintf("# Environment variables for %s in %s environment\n", projectName, envName))
    content.WriteString(fmt.Sprintf("# Generated by Radas CLI on %s\n\n", time.Now().Format(time.RFC3339)))
    
    // Sort keys for consistent output
    keys := make([]string, 0, len(envVars))
    for key := range envVars {
        keys = append(keys, key)
    }
    sort.Strings(keys)
    
    // Add each variable to the content
    for _, key := range keys {
        value := envVars[key]
        stringValue := fmt.Sprintf("%v", value)
        
        // Escape values with spaces or special characters
        if strings.ContainsAny(stringValue, " \n\t\"'$") {
            stringValue = fmt.Sprintf("\"%s\"", strings.ReplaceAll(stringValue, "\"", "\\\""))
        }
        
        content.WriteString(fmt.Sprintf("%s=%s\n", key, stringValue))
    }
    
    // Write to file
    err := os.WriteFile(filename, []byte(content.String()), 0644)
    if err != nil {
        return fmt.Errorf("error creating .env file: %v", err)
    }
    
    fmt.Printf("Environment variables saved to %s\n", filename)
    return nil
}
